version: "3"

services:

   rundeck:
      #servico rundeck
      #image: rewerdj/rundeck-wagner
      image: rundeck:3.0.20
      hostname: 192.168.56.105.nip.io
      ports:
        - 4440:4440
      build:
        context: .
     
